import test from 'node:test';
import assert from 'node:assert/strict';
import crypto from 'node:crypto';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { execFileSync } from 'node:child_process';
import { generateSshKeyPair, normalisePrivateKey, publicKeyOf } from './SshKeys.js';

/**
 * A key in the container ssh-keygen writes by default since OpenSSH 7.8 — the
 * file an operator actually has on disk. Generated by the real tool rather than
 * pasted as a fixture, so the test breaks if the tool changes its format.
 */
function opensshKey(passphrase = ''): string | undefined {
  const target = path.join(os.tmpdir(), `unikom-key-${crypto.randomUUID()}`);

  try {
    execFileSync('ssh-keygen', ['-t', 'ed25519', '-N', passphrase, '-C', 'probe', '-f', target], {
      stdio: 'ignore',
    });
  } catch {
    // No ssh-keygen on this machine; the PEM cases still cover the parser.
    return undefined;
  }

  try {
    return fs.readFileSync(target, 'utf8');
  } finally {
    fs.rmSync(target, { force: true });
    fs.rmSync(`${target}.pub`, { force: true });
  }
}

test('a generated pair yields a private key and an authorized_keys line', async () => {
  const pair = await generateSshKeyPair('unikom');

  assert.match(pair.privateKey, /^-----BEGIN RSA PRIVATE KEY-----/);
  assert.equal(pair.algorithm, 'ssh-rsa');
  assert.match(pair.publicKey, /^ssh-rsa [A-Za-z0-9+/=]+ unikom$/);
});

test('the public key is derived from the private one and stays the same', async () => {
  const pair = await generateSshKeyPair();
  const again = publicKeyOf(pair.privateKey);

  assert.equal(again.publicKey, pair.publicKey);
  assert.equal(again.algorithm, 'ssh-rsa');
});

test('a comment never breaks the line into a fourth field', async () => {
  const pair = await generateSshKeyPair('Kunde A Bestellungen');

  assert.equal(pair.publicKey.split(' ').length, 3);
  assert.ok(pair.publicKey.endsWith(' Kunde-A-Bestellungen'));
});

test('an unencrypted PEM key is accepted and normalised', () => {
  const { privateKey } = crypto.generateKeyPairSync('rsa', {
    modulusLength: 2048,
    privateKeyEncoding: { type: 'pkcs1', format: 'pem' },
    publicKeyEncoding: { type: 'pkcs1', format: 'pem' },
  });

  const normalised = normalisePrivateKey(privateKey);

  assert.equal(normalised.algorithm, 'ssh-rsa');
  assert.match(normalised.publicKey, /^ssh-rsa [A-Za-z0-9+/=]+$/);
});

test('a key with a passphrase is opened with it and stored without', () => {
  const { privateKey } = crypto.generateKeyPairSync('rsa', {
    modulusLength: 2048,
    privateKeyEncoding: { type: 'pkcs1', format: 'pem', cipher: 'aes-256-cbc', passphrase: 'sehr geheim' },
    publicKeyEncoding: { type: 'pkcs1', format: 'pem' },
  });

  assert.match(privateKey, /ENCRYPTED/);

  const normalised = normalisePrivateKey(privateKey, 'sehr geheim');

  assert.doesNotMatch(normalised.privateKey, /ENCRYPTED/);
  assert.equal(publicKeyOf(normalised.privateKey).publicKey, normalised.publicKey);
});

test('a missing or wrong passphrase says which of the two it is', () => {
  const { privateKey } = crypto.generateKeyPairSync('rsa', {
    modulusLength: 2048,
    privateKeyEncoding: { type: 'pkcs1', format: 'pem', cipher: 'aes-256-cbc', passphrase: 'sehr geheim' },
    publicKeyEncoding: { type: 'pkcs1', format: 'pem' },
  });

  assert.throws(() => normalisePrivateKey(privateKey), /mit einer Passphrase geschützt/);
  assert.throws(() => normalisePrivateKey(privateKey, 'daneben'), /mit dieser Passphrase nicht öffnen/);
});

test('a public key pasted by mistake is named as such', async () => {
  const pair = await generateSshKeyPair();

  assert.throws(() => normalisePrivateKey(pair.publicKey), /ist ein öffentlicher Schlüssel/);
});

test('anything that is not a key is refused, and nothing is empty', () => {
  assert.throws(() => normalisePrivateKey('   '), /kein Schlüsselmaterial/);
  assert.throws(() => normalisePrivateKey('Guten Tag'), /kein brauchbarer privater SSH-Schlüssel/);
});

test('the container ssh-keygen writes today is readable', (t) => {
  const material = opensshKey();

  if (!material) {
    t.skip('ssh-keygen is not available on this machine');
    return;
  }

  const normalised = normalisePrivateKey(material);
  assert.equal(normalised.algorithm, 'ssh-ed25519');
  assert.match(normalised.publicKey, /^ssh-ed25519 /);
});

test('an ssh-keygen key with a passphrase is readable too', (t) => {
  const material = opensshKey('sehr geheim');

  if (!material) {
    t.skip('ssh-keygen is not available on this machine');
    return;
  }

  assert.throws(() => normalisePrivateKey(material), /Passphrase/);
  assert.equal(normalisePrivateKey(material, 'sehr geheim').algorithm, 'ssh-ed25519');
});

/* ---- PuTTY ---------------------------------------------------------------
 *
 * The .ppk files below are built here rather than pasted in as fixtures, from
 * an RSA key this process just made. That keeps the test honest about the
 * format — it fails if the layout is misunderstood — and it needs no PuTTYgen
 * on the machine running it.
 */

function mpint(base64url: string): Buffer {
  const raw = Buffer.from(base64url, 'base64url');
  // A leading zero where the top bit is set, so the number stays positive.
  return raw[0] & 0x80 ? Buffer.concat([Buffer.from([0]), raw]) : raw;
}

function sshString(value: Buffer | string): Buffer {
  const body = Buffer.isBuffer(value) ? value : Buffer.from(value, 'utf8');
  const length = Buffer.alloc(4);
  length.writeUInt32BE(body.length);
  return Buffer.concat([length, body]);
}

function lines(blob: Buffer): { count: number; text: string } {
  const wrapped = (blob.toString('base64').match(/.{1,64}/g) ?? []).join('\n');
  return { count: wrapped.split('\n').length, text: wrapped };
}

/** A PuTTY private key file, version 2, optionally passphrase protected. */
function puttyKey(passphrase = '', comment = 'probe'): { ppk: string; openssh: string } {
  const { privateKey, publicKey } = crypto.generateKeyPairSync('rsa', {
    modulusLength: 2048,
    privateKeyEncoding: { type: 'pkcs1', format: 'pem' },
    publicKeyEncoding: { type: 'pkcs1', format: 'pem' },
  });

  const jwk = crypto.createPrivateKey(privateKey).export({ format: 'jwk' }) as Record<string, string>;
  const publicBlob = Buffer.concat([sshString('ssh-rsa'), sshString(mpint(jwk.e)), sshString(mpint(jwk.n))]);
  let privateBlob = Buffer.concat([
    sshString(mpint(jwk.d)),
    sshString(mpint(jwk.p)),
    sshString(mpint(jwk.q)),
    sshString(mpint(jwk.qi)),
  ]);

  const encryption = passphrase ? 'aes256-cbc' : 'none';
  const plain = passphrase
    ? Buffer.concat([privateBlob, Buffer.alloc((16 - (privateBlob.length % 16)) % 16)])
    : privateBlob;

  const macData = Buffer.concat([
    sshString('ssh-rsa'),
    sshString(encryption),
    sshString(comment),
    sshString(publicBlob),
    sshString(plain),
  ]);
  const macKey = crypto
    .createHash('sha1')
    .update('putty-private-key-file-mac-key')
    .update(passphrase)
    .digest();
  const mac = crypto.createHmac('sha1', macKey).update(macData).digest('hex');

  privateBlob = plain;

  if (passphrase) {
    const half = (suffix: number) => {
      const marker = Buffer.alloc(4);
      marker.writeUInt32BE(suffix);
      return crypto.createHash('sha1').update(marker).update(passphrase).digest();
    };
    const cipherKey = Buffer.concat([half(0), half(1)]).subarray(0, 32);
    const cipher = crypto.createCipheriv('aes-256-cbc', cipherKey, Buffer.alloc(16));
    cipher.setAutoPadding(false);
    privateBlob = Buffer.concat([cipher.update(plain), cipher.final()]);
  }

  const publicPart = lines(publicBlob);
  const privatePart = lines(privateBlob);

  const ppk = [
    'PuTTY-User-Key-File-2: ssh-rsa',
    `Encryption: ${encryption}`,
    `Comment: ${comment}`,
    `Public-Lines: ${publicPart.count}`,
    publicPart.text,
    `Private-Lines: ${privatePart.count}`,
    privatePart.text,
    `Private-MAC: ${mac}`,
    '',
  ].join('\n');

  return { ppk, openssh: publicKey };
}

test('a PuTTY key without a passphrase is accepted', () => {
  const { ppk } = puttyKey();

  const normalised = normalisePrivateKey(ppk);

  assert.equal(normalised.algorithm, 'ssh-rsa');
  // Ohne Kommentar: Der trägt beim Import nichts bei, und der Name des
  // Eintrags hängt ihn an, wenn die Zeile später abgefragt wird.
  assert.match(normalised.publicKey, /^ssh-rsa [A-Za-z0-9+/=]+$/);
  assert.doesNotMatch(normalised.privateKey, /PuTTY/);
  assert.match(normalised.privateKey, /^-----BEGIN RSA PRIVATE KEY-----/);
});

test('a PuTTY key and the same key as OpenSSH give the same public key', () => {
  const { ppk } = puttyKey();
  const normalised = normalisePrivateKey(ppk);

  // Derived twice by two roads: through the .ppk, and out of what we stored.
  assert.equal(publicKeyOf(normalised.privateKey).publicKey.split(' ').slice(0, 2).join(' '),
    normalised.publicKey.split(' ').slice(0, 2).join(' '));
});

test('a PuTTY key with a passphrase needs it, and the wrong one is refused', () => {
  const { ppk } = puttyKey('sehr geheim');

  assert.throws(() => normalisePrivateKey(ppk), /passphrase/i);
  assert.throws(() => normalisePrivateKey(ppk, 'daneben'), /passphrase/i);
  assert.equal(normalisePrivateKey(ppk, 'sehr geheim').algorithm, 'ssh-rsa');
});

test('a PuTTY key in version 3 names the two clicks that fix it', () => {
  const { ppk } = puttyKey();
  const version3 = ppk.replace('PuTTY-User-Key-File-2', 'PuTTY-User-Key-File-3');

  assert.throws(() => normalisePrivateKey(version3), /Version 3/);
  assert.throws(() => normalisePrivateKey(version3), /PPK-Version/);
  assert.throws(() => normalisePrivateKey(version3), /Export OpenSSH key/);
});

test('a PuTTY key of a type we cannot read says so instead of failing obscurely', () => {
  const { ppk } = puttyKey();
  const ed25519 = ppk.replace('PuTTY-User-Key-File-2: ssh-rsa', 'PuTTY-User-Key-File-2: ssh-ed25519');

  assert.throws(() => normalisePrivateKey(ed25519), /vom Typ ssh-ed25519/);
  assert.throws(() => normalisePrivateKey(ed25519), /Export OpenSSH key/);
});
